version: '3.8'

services:
  shopping-cart-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=shopping-cart
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mongodb
    networks:
      - shopping-cart-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mongodb:
    image: mongo:7.0
    container_name: shopping-cart-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=shopping-cart
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - shopping-cart-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  shopping-cart-network:
    driver: bridge
